name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Firebase CLI をインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Firebase Hosting にデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BANDMATCH_877 }}
          channelId: live
          projectId: bandmatch-877
